branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: upggraded-garbanzo
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: PHP 7.0
  default_region: south-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
